-- Create the portfolio table
CREATE TABLE IF NOT EXISTS public.portfolio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol text NOT NULL,
    entry_price double precision NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the watchlist table (for storing favorites)
CREATE TABLE IF NOT EXISTS public.watchlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) is recommended, but for now we'll allow public access 
-- if you haven't set up Authentication yet.
-- To allow public read/write (NOT SECURE for production, but okay for local prototype if Anon key has permissions):
ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.portfolio FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.portfolio FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.portfolio FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.portfolio FOR DELETE USING (true);

ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.watchlist FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.watchlist FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete access for all users" ON public.watchlist FOR DELETE USING (true);
